export * from './house/house.component';
export * from "./house-detail/house-detail.component";
export * from "./client/client.component";
export * from "./client-detail/client-detail.component";
export * from './assigment/assigment.component';
export * from './assigment-detail/assigment-detail.component';
export * from './house-selectable/house-selectable.component';
export * from './client-selectable/client-selectable.component';
export * from './assignment-schedule/assignment-schedule.component'
export * from './date-time-selectable/date-time-selectable.component'